name: "Build and test"
on:
  push:
    tags-ignore: ["*"] # tags run tagged-release workflow
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.16.2"
      - uses: actions/checkout@v2
      - run: make all
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: kubectl-schemahero
          path: bin/kubectl-schemahero
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: manager
          path: bin/manager

  test-postgres:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        postgres_version: ["10.16", "11.11", "12.6", "13.2"]
    steps:
      - uses: actions/checkout@v2
      - name: Download kubectl-schemahero binary
        uses: actions/download-artifact@v2.0.8
        with:
          name: kubectl-schemahero
          path: bin/
      - run: chmod +x bin/kubectl-schemahero
      - run: make -C integration/tests/postgres ${{matrix.postgres_version}}

  test-mysql:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        mysql_version: ["5.6.51", "5.7.33", "8.0.23"]
    steps:
      - uses: actions/checkout@v2
      - name: Download kubectl-schemahero binary
        uses: actions/download-artifact@v2.0.8
        with:
          name: kubectl-schemahero
          path: bin/
      - run: chmod +x bin/kubectl-schemahero
      - run: make -C integration/tests/mysql ${{matrix.mysql_version}}

  test-cockroach:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        cockroachdb_version: ["v19.2.12", "v20.1.13", "v20.2.6"]
    steps:
      - uses: actions/checkout@v2
      - name: Download kubectl-schemahero binary
        uses: actions/download-artifact@v2.0.8
        with:
          name: kubectl-schemahero
          path: bin/
      - run: chmod +x bin/kubectl-schemahero
      - run: make -C integration/tests/cockroach ${{matrix.cockroachdb_version}}

  test-cassandra:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        cassandra_version: ["3.11.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Download kubectl-schemahero binary
        uses: actions/download-artifact@v2.0.8
        with:
          name: kubectl-schemahero
          path: bin/
      - run: chmod +x bin/kubectl-schemahero
      - run: make -C integration/tests/cassandra ${{matrix.cassandra_version}}

  test-sqlite:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        sqlite_version: ["3.33.0"]
    steps:
      - uses: actions/checkout@v2
      - name: Download kubectl-schemahero binary
        uses: actions/download-artifact@v2.0.8
        with:
          name: kubectl-schemahero
          path: bin/
      - run: chmod +x bin/kubectl-schemahero
      - run: make -C integration/tests/sqlite ${{matrix.sqlite_version}}

